# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "lightmix-0.14.1-SpCovKo6AgBuGk0XzG_r_BzZaf3v-w2qjKOfVaV3jqWv";
    path = fetchzip {
      url = "https://github.com/haruki7049/lightmix/archive/refs/tags/0.14.1.tar.gz";
      hash = "sha256-qAW0Wm2C0dg/6SQelhaZvt+N2JZqzc3O3GEjZEimrNs=";
    };
  }
  {
    name = "riff_zig-0.2.1-J7H0A0x-AABK0wyA5y4uQxq5x95-RTPUGIwWd61cBTw7";
    path = fetchzip {
      url = "https://github.com/haruki7049/RIFF.zig/archive/refs/tags/0.2.1.tar.gz";
      hash = "sha256-qF3iKfj4RL8tLiy7K0MRdKBsuH1MosZu7DHTSmmzpN0=";
    };
  }
  {
    name = "zigggwavvv-0.3.0-iR5xWtfEAAAd1ca3u6kOrPIFzODMgHiUIZQWava6XIwD";
    path = fetchzip {
      url = "https://github.com/haruki7049/zigggwavvv/archive/refs/tags/0.3.0.tar.gz";
      hash = "sha256-NqcDSBngSK+7emPru4bTN/fqsoPA4zg90HkIMYJXygw=";
    };
  }
]
