# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "known_folders-0.0.0-Fy-PJtTTAADUOhGKM0sxzG4eMkNQxRvx9e5dfHVyaeA3";
    path = fetchzip {
      url = "https://github.com/ziglibs/known-folders/archive/ab5cf5feb936fa3b72c95d3ad0c0c67791937ba1.tar.gz";
      hash = "sha256-Pdn/nUclhHBB1COTzNNR5ysE13h6uLOFJjuFrasv/2I=";
    };
  }
  {
    name = "lightmix-0.12.0-SpCovPiDAgBLZjNJ_IS755eoWzK9U1YyS4ehj36S8Ivs";
    path = fetchzip {
      url = "https://github.com/haruki7049/lightmix/archive/refs/tags/0.12.0.tar.gz";
      hash = "sha256-tX6PNVdFxKFTLpOvplpDMWZnEsiCPGHBAmtjlGKtLc0=";
    };
  }
  {
    name = "lightmix_wav-0.5.0-IIrulooTVQD9sWDdiGai2Ix5sP7uzZ8YrBY1oGt0BhKz";
    path = fetchzip {
      url = "https://github.com/haruki7049/lightmix_wav/archive/refs/tags/0.5.0.tar.gz";
      hash = "sha256-QYreiBlcMnKuYbiyWqgThVsXJ0Xs3dQMwvMcJ7A66o8=";
    };
  }
]
