# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "lightmix-0.15.0-SpCovIlLAgA2fVG1rWRTstjLoMIh7AIXmaHnPrALkK8o";
    path = fetchzip {
      url = "https://github.com/haruki7049/lightmix/archive/refs/tags/0.15.0.tar.gz";
      hash = "sha256-qbTRHjMwaQwJfbh3DweZWvfr05/NLloUanjRcUC9c0E=";
    };
  }
  {
    name = "lightmix_filters-0.0.0-QAX9gdIPIgBCp_p3e-NN9nsTq9HRZgV84WROpr60arbN";
    path = fetchzip {
      url = "https://github.com/haruki7049/lightmix_filters/archive/7a2a91439f47f28a479226838d94eb875c5c1a56.tar.gz";
      hash = "sha256-Y9r/m3Aochkjz+4tXHts22Q5uJn4dhvslBWN/bawv0Q=";
    };
  }
  {
    name = "riff_zig-0.2.1-J7H0A0x-AABK0wyA5y4uQxq5x95-RTPUGIwWd61cBTw7";
    path = fetchzip {
      url = "https://github.com/haruki7049/RIFF.zig/archive/refs/tags/0.2.1.tar.gz";
      hash = "sha256-qF3iKfj4RL8tLiy7K0MRdKBsuH1MosZu7DHTSmmzpN0=";
    };
  }
  {
    name = "zigggwavvv-0.3.0-iR5xWtfEAAAd1ca3u6kOrPIFzODMgHiUIZQWava6XIwD";
    path = fetchzip {
      url = "https://github.com/haruki7049/zigggwavvv/archive/refs/tags/0.3.0.tar.gz";
      hash = "sha256-NqcDSBngSK+7emPru4bTN/fqsoPA4zg90HkIMYJXygw=";
    };
  }
]
